-- Yacht Knowledge Pack V1
-- Broad professional yacht-industry knowledge foundation for Yacht Broker Agent.
-- Safe to rerun: entries are inserted only when the same title is not already present for this agent.

create extension if not exists pgcrypto;

create or replace function public.seed_yacht_knowledge_pack_v1(
  p_title text,
  p_category text,
  p_summary text,
  p_content text,
  p_source text,
  p_reliability text,
  p_tags text[] default '{}'::text[]
) returns void language plpgsql as $$
begin
  insert into knowledge_entries (id, agent_id, title, category, summary, content, source, reliability_level, tags, created_at, updated_at)
  select gen_random_uuid(), 'yacht-broker-agent', p_title, p_category, p_summary, p_content, p_source, p_reliability, p_tags, now(), now()
  where not exists (
    select 1 from knowledge_entries
    where agent_id = 'yacht-broker-agent' and title = p_title
  );
end;
$$;

select public.seed_yacht_knowledge_pack_v1('Professional Advisory Boundary for Yacht Brokerage', 'Advisory Boundaries', 'The broker agent may educate, qualify and draft, but must not give final legal, tax, flag, class, insurance or regulatory advice.', $$Use knowledge as professional operating context. The agent can explain common yacht transaction concepts, ask for missing facts and prepare safe drafts. It must route legal, tax, customs, flag-state, class, insurance, sanctions and employment questions to specialist review before external advice is sent.$$, 'internal operating policy', 'verified', array['boundary','legal','tax','flag','class','insurance','approval']);

select public.seed_yacht_knowledge_pack_v1('Buyer Qualification Framework V1', 'Brokerage Process', 'Core buyer checks before any sensitive opportunity is disclosed.', $$Qualify budget range, proof-of-funds path, decision authority, purchase timeline, preferred yacht size and type, builder preferences, cruising region, private or commercial use, ownership structure, broker representation, NDA willingness and decision process. Ask only for missing items and never disclose private yacht identity, owner details, exact location or documents before approval.$$, 'internal brokerage baseline', 'verified', array['buyer','qualification','pof','nda','confidentiality']);

select public.seed_yacht_knowledge_pack_v1('Seller Qualification Framework V1', 'Brokerage Process', 'Core seller checks before accepting, valuing or marketing a yacht.', $$Verify authority to sell, beneficial ownership or representative authority, central agency or open listing status, asking expectations, location, VAT or tax status if known, flag and class status, documents available, media permissions, confidentiality requirements, urgency, debt or distressed context and broker cooperation terms.$$, 'internal brokerage baseline', 'verified', array['seller','mandate','valuation','documents','confidentiality']);

select public.seed_yacht_knowledge_pack_v1('Broker Cooperation Framework V1', 'Brokerage Process', 'How to handle broker-to-broker enquiries safely.', $$For broker enquiries, confirm mandate or buyer representation, buyer qualification, confidentiality expectations, commission framework for review, non-circumvention sensitivities, source of enquiry and whether the broker can provide proof of authority. Do not discuss commercial split or disclose sensitive assets without admin approval.$$, 'internal brokerage baseline', 'verified', array['broker','cooperation','mandate','commission','approval']);

select public.seed_yacht_knowledge_pack_v1('Yacht Brokerage Deal Flow V1', 'Brokerage Process', 'Standard yacht sale flow from initial enquiry to closing.', $$Typical flow: enquiry, classification, lead qualification, NDA when needed, controlled disclosure, inspection planning, LOI or offer, deposit and escrow discussion, survey and sea trial, condition resolution, MOA or SPA, closing documents, registry changes, delivery and handover. Sensitive steps require approval.$$, 'internal brokerage baseline', 'high', array['deal-flow','closing','survey','moa','spa']);

select public.seed_yacht_knowledge_pack_v1('Off-Market Disclosure Levels V1', 'Off-Market Deals', 'Layered disclosure model for private yacht opportunities.', $$Level 1: generic profile only. Level 2: anonymized technical and commercial outline. Level 3: yacht identity after buyer review and NDA. Level 4: documents, exact location and owner-side data only after approval. The agent must never skip levels automatically.$$, 'internal confidentiality baseline', 'verified', array['off-market','confidentiality','nda','disclosure']);

select public.seed_yacht_knowledge_pack_v1('NDA and Controlled Disclosure Workflow V1', 'Documents and Disclosure', 'When and how an NDA step should be proposed.', $$An NDA is appropriate before disclosing off-market identity, owner data, exact berth, technical files, surveys, class reports, financial documents, photographs not approved for publication or sensitive commercial terms. The agent may propose an NDA ToolRequest, but must not send or sign documents automatically.$$, 'internal document baseline', 'verified', array['nda','documents','approval','off-market']);

select public.seed_yacht_knowledge_pack_v1('Yacht Document Request Checklist', 'Documents and Disclosure', 'Documents commonly requested during yacht sale due diligence.', $$Common due diligence materials may include registry certificate, title documents, class certificates, safety certificates, insurance, maintenance records, refit invoices, engine logs, GA plans, inventory, survey reports, crew/management records, VAT/tax documents if available and ownership authority. Sensitive documents require controlled release and approval.$$, 'internal due diligence baseline', 'high', array['documents','due-diligence','survey','class','approval']);

select public.seed_yacht_knowledge_pack_v1('LOI Awareness for Yacht Transactions', 'Contracts and Deal Flow', 'High-level understanding of letters of intent.', $$A letter of intent usually records commercial intent, price, deposit concept, conditions, survey expectations, timing, confidentiality and exclusivity assumptions. It may or may not be binding depending on wording and law. The agent may summarize requested deal points but must not draft binding legal language without review.$$, 'internal legal-boundary baseline', 'high', array['loi','offer','legal-boundary']);

select public.seed_yacht_knowledge_pack_v1('MOA and SPA Awareness for Yacht Transactions', 'Contracts and Deal Flow', 'High-level understanding of formal yacht sale agreements.', $$MOA or SPA documents may govern price, deposit, conditions, inspection, survey, closing location, delivery, warranties, default, title transfer and governing law. The agent should treat them as legal documents and route drafting, revision or interpretation to approved human/legal review.$$, 'internal legal-boundary baseline', 'high', array['moa','spa','contract','closing']);

select public.seed_yacht_knowledge_pack_v1('Escrow and Deposit Safety Rules', 'Contracts and Deal Flow', 'Operational awareness for deposits and escrow without giving payment instructions.', $$Deposits are often held by an agreed escrow stakeholder under transaction documents. The agent must not provide bank details, payment instructions, refund promises, escrow terms or closing mechanics. It may identify that escrow/deposit review is needed and propose an approval/task.$$, 'internal financial-boundary baseline', 'verified', array['escrow','deposit','payment','approval']);

select public.seed_yacht_knowledge_pack_v1('Survey and Sea Trial Process Awareness', 'Classification and Survey', 'How survey and sea trial affect yacht transactions.', $$Survey and sea trial can reveal technical defects, class issues, machinery concerns, performance variance, safety deficiencies and maintenance gaps. Findings can affect acceptance, renegotiation, repair obligations, timing or withdrawal. The agent should ask whether survey conditions and known defects are disclosed.$$, 'internal technical baseline', 'high', array['survey','sea-trial','technical','closing']);

select public.seed_yacht_knowledge_pack_v1('Class Society Transaction Awareness', 'Classification and Survey', 'Role of class status in yacht acquisition and sale.', $$Class status can affect buyer confidence, insurance, financing, commercial operation and technical risk. Capture class society, notation, survey status, overdue recommendations, exemptions, damage history and whether the yacht is maintained in class. Final class interpretation requires surveyor/class review.$$, 'https://iacs.org.uk', 'high', array['class','survey','technical','insurance']);

select public.seed_yacht_knowledge_pack_v1('Flag State Basics for Yacht Brokers', 'Flags and Registration', 'What flag state means commercially and operationally.', $$A yacht flag determines nationality and the administrative framework for registration, certificates and oversight. Flag can affect private/commercial use, surveys, manning, mortgage recording, charter permissions, documentation and owner structure. The agent should collect facts and route final flag advice to specialists.$$, 'https://www.imo.org', 'high', array['flag','registration','certificate','advisory-boundary']);

select public.seed_yacht_knowledge_pack_v1('Private vs Commercial Yacht Use', 'Charter Operations', 'Why intended use must be qualified early.', $$Private use generally means owner and guest use without commercial charter. Commercial use can trigger coding, surveys, crew requirements, insurance, charter contracts, tax/customs consequences and flag requirements. The agent must ask intended use early and avoid confirming charter legality without specialist review.$$, 'internal compliance baseline', 'high', array['private-use','commercial-use','charter','compliance']);

select public.seed_yacht_knowledge_pack_v1('Charter Capability Qualification Questions', 'Charter Operations', 'Questions before discussing charter operation or income.', $$Ask flag, location, coding/commercial status, crew arrangement, management company, insurance, charter area, VAT/customs position, existing charter contracts and recent compliance history. Do not state that a yacht is charter-ready or legal for charter without documents and approval.$$, 'internal charter baseline', 'high', array['charter','commercial-use','insurance','tax','approval']);

select public.seed_yacht_knowledge_pack_v1('VAT and Tax Boundary for Yacht Brokerage', 'Tax, VAT and Customs', 'Safe handling of VAT and tax questions.', $$VAT, import status, temporary admission, charter tax treatment and ownership structures are jurisdiction-specific and fact-sensitive. The agent may collect facts and explain that specialist review is needed, but must not promise VAT-paid status, tax treatment or customs eligibility without documents.$$, 'internal tax-boundary baseline', 'verified', array['vat','tax','customs','boundary']);

select public.seed_yacht_knowledge_pack_v1('Temporary Admission Awareness', 'Tax, VAT and Customs', 'High-level awareness of temporary admission concepts.', $$Temporary admission may be relevant when non-local owners bring yachts into certain customs territories for limited periods. Eligibility can depend on owner residence, flag, use, itinerary, beneficial ownership and local rules. Treat all such statements as requiring customs/tax review.$$, 'internal customs baseline', 'medium', array['temporary-admission','customs','tax']);

select public.seed_yacht_knowledge_pack_v1('KYC and Beneficial Ownership Checks', 'KYC, AML and Sanctions', 'Identity and ownership checks before sensitive transaction work.', $$Capture legal buyer or seller identity, beneficial owner, representative authority, source-of-funds path, corporate structure, sanctions exposure, politically exposed person concerns and bank/payment complexity. High-risk or unclear items require admin review before sensitive disclosure or deal progression.$$, 'internal AML baseline', 'verified', array['kyc','aml','beneficial-owner','source-of-funds']);

select public.seed_yacht_knowledge_pack_v1('Sanctions Screening Trigger Points', 'KYC, AML and Sanctions', 'When sanctions review must be escalated.', $$Escalate if a party, beneficial owner, vessel, flag, current location, bank, manager, charterer or counterparty has exposure to sanctioned jurisdictions, blocked persons, opaque ownership, unusual payment routes or high-risk intermediaries. Do not continue sensitive disclosure until cleared.$$, 'internal AML baseline', 'verified', array['sanctions','aml','risk','approval']);

select public.seed_yacht_knowledge_pack_v1('SOLAS Awareness for Yacht Brokers', 'Safety and Compliance', 'Safety convention awareness for larger or commercial vessels.', $$SOLAS is a major international safety convention. Applicability depends on vessel type, size, tonnage, use, flag implementation and certificates. The agent should not determine applicability alone; it should collect length, tonnage, use, flag and certificate data for specialist review.$$, 'https://www.imo.org/en/About/Conventions/Pages/International-Convention-for-the-Safety-of-Life-at-Sea-(SOLAS),-1974.aspx', 'high', array['solas','safety','compliance','certificate']);

select public.seed_yacht_knowledge_pack_v1('MARPOL Awareness for Yacht Brokers', 'Safety and Compliance', 'Pollution prevention awareness for yacht operations and transactions.', $$MARPOL concerns pollution prevention from ships. In yacht brokerage, ask about waste systems, fuel, sewage, garbage, certificates, pollution-related deficiencies and operational history when relevant. Do not provide final regulatory interpretation without flag/class review.$$, 'https://www.imo.org/en/About/Conventions/Pages/International-Convention-for-the-Prevention-of-Pollution-from-Ships-(MARPOL).aspx', 'high', array['marpol','pollution','compliance','certificate']);

select public.seed_yacht_knowledge_pack_v1('MLC Crew Compliance Awareness', 'Crew and Operations', 'Crew welfare and employment framework awareness.', $$The Maritime Labour Convention can be relevant to commercially operated yachts and crew employment conditions. The agent should capture crew arrangement, management company, commercial use, employment/document status and any crew-related disputes, then escalate compliance questions.$$, 'https://www.ilo.org/global/standards/maritime-labour-convention', 'high', array['mlc','crew','employment','compliance']);

select public.seed_yacht_knowledge_pack_v1('ISM and Safety Management Awareness', 'Crew and Operations', 'Safety management system awareness.', $$Safety management systems can be relevant for commercial operation and larger yachts. Ask who manages operations, whether SMS/ISM documents exist, whether a DPA is appointed if applicable and whether recent audits or deficiencies exist. Do not certify compliance.$$, 'https://www.imo.org', 'medium', array['ism','sms','safety-management','compliance']);

select public.seed_yacht_knowledge_pack_v1('ISPS Security Awareness', 'Safety and Compliance', 'Security framework awareness where applicable.', $$The International Ship and Port Facility Security Code may be relevant for some commercial vessels and port interactions. If a client asks about security compliance, collect vessel type, commercial status, flag, trading area and certificates, then escalate to specialist review.$$, 'https://www.imo.org', 'medium', array['isps','security','compliance']);

select public.seed_yacht_knowledge_pack_v1('Insurance Placement Fact Pattern', 'Insurance and Risk', 'Facts needed before discussing yacht insurance.', $$Insurance review may depend on value, navigation area, private/commercial use, crew, flag, class, claims history, survey findings, wintering plans, management company, owner profile and intended activities. The agent must not promise coverage, premiums or warranty compliance.$$, 'internal insurance baseline', 'high', array['insurance','risk','survey','flag']);

select public.seed_yacht_knowledge_pack_v1('Yacht Valuation Factors', 'Valuation and Market', 'Main inputs that influence yacht pricing and market position.', $$Valuation depends on builder, model, year, length, volume, condition, refit history, engine hours, class and flag status, pedigree, layout, location, seasonality, comparable listings, confirmed sales, seller motivation and survey findings. Avoid exact valuation claims without data.$$, 'internal valuation baseline', 'high', array['valuation','market','comparable-sales']);

select public.seed_yacht_knowledge_pack_v1('Comparable Sales Discipline', 'Valuation and Market', 'How to treat yacht comparable data.', $$Distinguish asking prices, reductions, achieved sale prices, private discounts and rumored transactions. Mark source reliability. Do not present unverifiable market chatter as fact. Explain that confidential final prices may differ from published asking prices.$$, 'internal valuation baseline', 'high', array['comparables','valuation','market-intelligence']);

select public.seed_yacht_knowledge_pack_v1('Refit History and Maintenance Records', 'Refit and Technical', 'Why refit and maintenance history matter in brokerage.', $$Recent refits can support value and buyer confidence only if scope, yard, invoices, warranties, class impact and technical records are clear. Missing records, vague refit claims or cosmetic-only work should be treated cautiously in draft language.$$, 'internal technical baseline', 'high', array['refit','maintenance','technical','valuation']);

select public.seed_yacht_knowledge_pack_v1('Technical Red Flags in Yacht Brokerage', 'Refit and Technical', 'Technical issues that should trigger deeper review.', $$Red flags include overdue class items, major engine issues, stabilizer problems, corrosion, osmosis on composites, water ingress, generator unreliability, poor records, accident history, incomplete refit, title/document gaps and unusually low asking price. Route technical claims to survey review.$$, 'internal technical baseline', 'high', array['technical-risk','survey','red-flags']);

select public.seed_yacht_knowledge_pack_v1('Crew and Management Due Diligence', 'Crew and Operations', 'Operational management questions for buyers and sellers.', $$Ask whether a yacht has a management company, captain, crew contracts, payroll provider, ISM/SMS responsibilities where applicable, maintenance scheduling, operating budget, cruising program and handover plan. Crew and employment issues can affect deal risk and continuity.$$, 'internal operations baseline', 'high', array['crew','management','operations']);

select public.seed_yacht_knowledge_pack_v1('Delivery and Handover Checklist', 'Crew and Operations', 'Operational items around closing and handover.', $$Handover may include delivery location, crew transition, fuel, spares, manuals, certificates, keys, tenders/toys, inventory, insurance start, registry changes, management setup, berth arrangements and agreed closing conditions. Sensitive timing and payment instructions require approval.$$, 'internal operations baseline', 'high', array['handover','delivery','closing']);

select public.seed_yacht_knowledge_pack_v1('Marina and Berthing Constraints', 'Marinas and Berthing', 'Why berth availability can affect yacht acquisition.', $$Berthing can be constrained by length, beam, draft, season, location, marina waitlists, commercial use, insurance and local permits. For buyers, ask intended home port, cruising region and seasonal berth needs early.$$, 'internal operations baseline', 'medium', array['berthing','marina','operations']);

select public.seed_yacht_knowledge_pack_v1('Yacht Segment Overview', 'Yacht Market Segments', 'Basic segmentation for brokerage conversations.', $$Useful segments include production motor yachts, semi-custom yachts, full-custom superyachts, explorer yachts, sailing yachts, catamarans, support vessels and chase boats. Segment affects builder set, market depth, survey focus, crew, operating budget and buyer expectations.$$, 'internal market baseline', 'medium', array['segments','market','builder']);

select public.seed_yacht_knowledge_pack_v1('Major Builder Awareness', 'Yacht Market Segments', 'How to discuss builders without overclaiming.', $$Builders vary by size range, construction material, style, pedigree, resale liquidity, customization, after-sales support and market perception. The agent may discuss builder preference as a qualification point but should avoid unsupported claims about quality, availability or value without current market evidence.$$, 'internal market baseline', 'medium', array['builders','market','valuation']);

select public.seed_yacht_knowledge_pack_v1('Family Office Buyer Communication Style', 'Client Communication', 'How to handle family office yacht acquisition enquiries.', $$Family office enquiries often value discretion, efficient qualification, documented process, confidentiality and clear next steps. The agent should be concise, avoid hype, confirm authority and proof-of-funds path politely, and propose a controlled call or NDA step where appropriate.$$, 'internal communication baseline', 'high', array['family-office','buyer','tone']);

select public.seed_yacht_knowledge_pack_v1('UHNW Buyer Objection Handling', 'Client Communication', 'Common buyer objections and safe responses.', $$Common objections include confidentiality, time pressure, proof-of-funds sensitivity, broker representation, desire for off-market access, concern over valuation and reluctance to sign NDA. Respond by explaining process, confidentiality, controlled disclosure and the reason each step protects both sides.$$, 'internal communication baseline', 'high', array['buyer','objections','communication']);

select public.seed_yacht_knowledge_pack_v1('Seller Objection Handling', 'Client Communication', 'Common seller objections and safe responses.', $$Sellers may resist valuation realism, document requests, confidentiality limits, commission discussion, media restrictions or buyer qualification. Respond by explaining that qualified process protects price, discretion and transaction certainty. Avoid promising sale price or timing.$$, 'internal communication baseline', 'high', array['seller','objections','communication']);

select public.seed_yacht_knowledge_pack_v1('Commission Discussion Safety', 'Contracts and Deal Flow', 'How to treat commission and commercial terms.', $$Commission, fee splits, central agency terms, broker cooperation and success fees are commercially sensitive. The agent may acknowledge the topic and propose admin review, but must not agree terms, quote binding percentages or confirm commission structures without approval.$$, 'internal commercial-boundary baseline', 'verified', array['commission','broker','approval']);

select public.seed_yacht_knowledge_pack_v1('Confidential Draft Reply Style Guide', 'Client Communication', 'Professional tone for yacht brokerage replies.', $$Use concise, formal, discreet language. Avoid hype, pressure, apologies, AI disclaimers and unsupported claims. State one controlled next step. Withhold sensitive asset, owner, location, document and commercial details until qualification and approval.$$, 'internal communication baseline', 'verified', array['draft','tone','confidentiality']);

select public.seed_yacht_knowledge_pack_v1('Risk Escalation Triggers for Yacht Broker Agent', 'Approval and Risk', 'Signals that should increase risk and approval attention.', $$Escalate for requests involving owner identity, yacht identity, exact location, documents, bank/payment details, commission terms, legal/tax/flag advice, sanctions exposure, distressed seller claims, unusual urgency, unclear authority, politically exposed persons or attempts to bypass NDA/approval.$$, 'internal risk baseline', 'verified', array['risk','approval','escalation']);

select public.seed_yacht_knowledge_pack_v1('Source Reliability Rules for Yacht Knowledge', 'Advisory Boundaries', 'How the agent should trust and cite stored yacht knowledge.', $$Prefer official registries, government maritime authorities, IMO/ILO publications, class society documents, signed deal documents and verified internal policy. Treat broker blogs, marketing pages and market gossip as lower reliability unless independently confirmed. Preserve source and date when adding knowledge.$$, 'internal source policy', 'verified', array['source','reliability','knowledge']);

select public.seed_yacht_knowledge_pack_v1('Knowledge Update Workflow for Yacht Topics', 'Advisory Boundaries', 'How new yacht knowledge should be added later.', $$For new topics, capture source URL, publication date, jurisdiction, summary, operational use, risk level and approval requirement. Legal, tax, compliance and flag content should be stored as awareness and escalation guidance, not final advice.$$, 'internal source policy', 'verified', array['knowledge','review','governance']);

select public.seed_yacht_knowledge_pack_v1('Flag Registry Cayman Islands Awareness', 'Flags and Registration', 'Cayman Islands is a common yacht registry reference point.', $$Cayman Islands is a prominent yacht registry. For Cayman-related questions, verify current registration type, vessel eligibility, required documents, surveys, ownership structure and private or commercial status with the Cayman Islands Shipping Registry or specialist counsel.$$, 'https://www.cishipping.com', 'high', array['flag','cayman','registration']);

select public.seed_yacht_knowledge_pack_v1('Flag Registry Marshall Islands Awareness', 'Flags and Registration', 'Marshall Islands is a common yacht registry reference point.', $$The Republic of the Marshall Islands registry is often used for yachts and commercial vessels. For RMI-related questions, verify current yacht registration requirements, ownership entity, private or commercial status, mortgage recording and certificate requirements with the official registry or specialist counsel.$$, 'https://www.register-iri.com/yachts/', 'high', array['flag','marshall-islands','registration']);

select public.seed_yacht_knowledge_pack_v1('Flag Registry Malta Awareness', 'Flags and Registration', 'Malta is a common EU yacht registration and commercial yacht reference point.', $$Malta is frequently relevant for yacht registration and commercial yacht structures. For Malta-related questions, verify current Transport Malta requirements, commercial yacht code status, VAT/tax facts, ownership and operating model with official sources or specialist counsel.$$, 'https://www.transport.gov.mt/maritime', 'high', array['flag','malta','registration','vat']);

select public.seed_yacht_knowledge_pack_v1('Red Ensign Group Yacht Code Awareness', 'Flags and Registration', 'Reference point for large yachts under Red Ensign Group administrations.', $$The Red Ensign Group Yacht Code is a key reference for large yacht standards under participating UK-related registries. Use it as a signpost for compliance questions, not as final technical advice. Confirm current version and applicable flag administration.$$, 'https://www.gov.uk/government/publications/the-red-ensign-group-yacht-code', 'high', array['red-ensign','flag','code','compliance']);

drop function public.seed_yacht_knowledge_pack_v1(text, text, text, text, text, text, text[]);
