-- Yacht Broker Agent A-Z foundation knowledge seed.
-- Safe to rerun: entries are inserted only when the same title is not already present for this agent.

create extension if not exists pgcrypto;

create or replace function public.seed_agent_knowledge_entry(
  p_agent_id text,
  p_title text,
  p_category text,
  p_summary text,
  p_content text,
  p_source text,
  p_reliability text
) returns void language plpgsql as $$
begin
  insert into knowledge_entries (id, agent_id, title, category, summary, content, source, reliability_level, tags, created_at, updated_at)
  select gen_random_uuid(), p_agent_id, p_title, p_category, p_summary, p_content, p_source, p_reliability, '{}'::text[], now(), now()
  where not exists (
    select 1 from knowledge_entries
    where agent_id = p_agent_id and title = p_title
  );
end;
$$;

select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Yacht Brokerage A-Z: Advisory Boundary', 'Advisory Boundaries', 'The agent may educate and draft, but must not provide final legal, tax, flag, class or insurance advice.', $$Use yacht knowledge as operational context. For legal, tax, flag-state, class, insurance, customs, sanctions or employment matters, the agent should explain the issue at a high level, ask for missing facts and route the matter to specialist review before any external advice is sent.$$, 'internal operating rule', 'verified');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Brokerage Deal Flow Overview', 'Brokerage Process', 'Standard yacht sale flow from inquiry to closing.', $$Typical flow: inquiry, lead review, buyer or seller checks, NDA where needed, controlled disclosure, offer or LOI, deposit and escrow discussion, survey and sea trial, condition resolution, closing documents, registry changes, delivery and handover. Sensitive steps require approval.$$, 'internal brokerage baseline', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Buyer Due Diligence Checklist', 'Brokerage Process', 'Core buyer checks before presenting sensitive yacht opportunities.', $$Capture budget range, decision maker, timeline, desired size and type, cruising region, private or charter use, financing plan, proof-of-funds path, broker representation, nationality or ownership structure considerations and NDA willingness. Do not disclose private yacht identity before checks and approval.$$, 'internal brokerage baseline', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Seller Mandate Checklist', 'Brokerage Process', 'Core seller-side checks before accepting or marketing a yacht.', $$Verify authority to sell, ownership position, existing central agency or open listing, asking expectation, location, documents available, class and flag status, VAT/tax statement if known, confidentiality level, media permissions, urgency, debt or distressed context and cooperation terms.$$, 'internal brokerage baseline', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Off-Market Disclosure Levels', 'Off-Market Deals', 'Layered disclosure model for private deals.', $$Level 1: generic profile only. Level 2: anonymized technical/commercial outline. Level 3: yacht identity after buyer review and NDA. Level 4: documents, exact location and owner-side data only after approval. The agent should never jump levels automatically.$$, 'internal confidentiality baseline', 'verified');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'LOI, MOA and SPA Awareness', 'Contracts and Deal Flow', 'High-level distinction between intent, sale agreement and closing documents.', $$An LOI usually records commercial intent and key deal points. MOA or SPA documents carry more formal sale terms, conditions, deposits, closing mechanics and default consequences. The agent may summarize requested terms but must not draft binding legal language without approval.$$, 'internal legal-boundary baseline', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Escrow and Deposit Awareness', 'Contracts and Deal Flow', 'Operational awareness for deposits and escrow.', $$Yacht purchases often involve deposits held by an escrow stakeholder under agreed terms. The agent must not provide payment instructions, bank details, escrow terms, refund promises or closing mechanics without admin and legal review.$$, 'internal legal-boundary baseline', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Survey and Sea Trial Deal Impact', 'Classification and Survey', 'How survey and sea trial affect a yacht transaction.', $$Survey and sea trial findings can affect acceptance, price renegotiation, repairs, withdrawal rights and closing timing. The agent should ask whether survey conditions, class status, engine hours, maintenance history and known defects have been disclosed.$$, 'internal technical baseline', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Class Society Awareness', 'Classification and Survey', 'Role of class societies in yacht transactions.', $$Classification societies set and verify technical standards for vessels within class. A yacht being in class can affect insurance, commercial operation, financing, survey expectations and buyer confidence. The agent should capture class society, notation, survey status and any overdue recommendations.$$, 'https://iacs.org.uk', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Flag State Basics', 'Flags and Registration', 'What a flag state means for a yacht.', $$A yacht flag determines nationality and the flag-state framework for registration, certificates and operational oversight. Flag choice can affect private versus commercial use, surveys, crew, mortgage recording, charter permissions and owner structure. Final flag advice requires specialist review.$$, 'https://www.imo.org', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Red Ensign Group Yacht Code Awareness', 'Flags and Registration', 'Reference point for large yachts under Red Ensign Group administrations.', $$The Red Ensign Group Yacht Code is a key reference for large yacht standards under participating UK-related registries. The agent should use it as a signpost for compliance questions, not as final technical advice. Confirm current code version and applicable flag administration.$$, 'https://www.gov.uk/government/publications/the-red-ensign-group-yacht-code', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Large Commercial Yacht Code LY3 Awareness', 'Safety and Compliance', 'UK MCA reference for large commercial yachts.', $$The MCA Large Commercial Yacht Code LY3 is an important reference for commercial yacht safety standards. For a transaction, capture whether the yacht is private or commercial, its flag, tonnage, length, certification status and whether a newer code applies.$$, 'https://www.gov.uk/government/publications/large-commercial-yacht-code-ly3', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Private vs Commercial Yacht Use', 'Charter Operations', 'Operational distinction that changes compliance and deal risk.', $$Private use generally means use by owner and guests without commercial charter. Commercial use can trigger coding, surveys, crew, insurance, tax, customs and flag requirements. The agent must ask intended use early and avoid confirming charter legality without review.$$, 'internal compliance baseline', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Charter Compliance Questions', 'Charter Operations', 'Questions to ask before discussing charter capability.', $$Ask flag, location, coding status, commercial registration, crew status, insurance, charter area, VAT/customs position, management company and whether charter contracts are already in use. Do not state that a yacht is legal for charter without documentation and approval.$$, 'internal charter baseline', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'VAT and Tax Boundary', 'Tax, VAT and Customs', 'How to handle VAT and tax questions safely.', $$VAT, import status, temporary admission, ownership structure and charter tax treatment are jurisdiction-specific and fact-sensitive. The agent may collect facts and explain that review is needed, but must not give final tax advice or promise VAT-paid status without documents.$$, 'internal tax-boundary baseline', 'verified');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Temporary Admission Awareness', 'Tax, VAT and Customs', 'High-level concept relevant to non-EU owners and cruising.', $$Temporary admission can be relevant when non-local owners bring yachts into certain customs territories for limited periods. Eligibility depends on owner, use, flag, residence, itinerary and local rules. Treat all statements as needing tax/customs review.$$, 'internal customs baseline', 'medium');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'SOLAS Awareness for Yachts', 'Safety and Compliance', 'Safety convention awareness for larger or commercial vessels.', $$SOLAS is a major international safety convention. Applicability depends on vessel type, size, use and flag implementation. The agent should not determine applicability alone; it should collect length, tonnage, use, flag and certificate data for specialist review.$$, 'https://www.imo.org/en/About/Conventions/Pages/International-Convention-for-the-Safety-of-Life-at-Sea-(SOLAS),-1974.aspx', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'MARPOL Awareness for Yachts', 'Safety and Compliance', 'Pollution prevention awareness for yacht operations and transactions.', $$MARPOL concerns pollution prevention from ships. For yacht brokerage, ask about waste systems, fuel, sewage, garbage, certificates and any pollution-related deficiencies. Do not provide final regulatory interpretation without flag/class review.$$, 'https://www.imo.org/en/About/Conventions/Pages/International-Convention-for-the-Prevention-of-Pollution-from-Ships-(MARPOL).aspx', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'MLC Crew Awareness', 'Crew and Operations', 'Crew welfare and employment framework awareness.', $$The Maritime Labour Convention can be relevant to commercially operated yachts and crew employment conditions. The agent should capture crew arrangement, management company, commercial use and employment/document status, and escalate labor compliance questions.$$, 'https://www.ilo.org/global/standards/maritime-labour-convention', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'ISM and Safety Management Awareness', 'Crew and Operations', 'Safety management system awareness.', $$A safety management system can be relevant for commercial operation and larger yachts. The agent should ask who manages operations, whether SMS/ISM documents exist, who is the DPA if applicable and whether recent audits or deficiencies exist.$$, 'https://www.imo.org', 'medium');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Insurance Placement Questions', 'Insurance and Risk', 'Facts needed before discussing yacht insurance.', $$Insurance review may depend on value, navigation area, crew, private/commercial use, flag, class, claims history, survey findings, wintering plans and owner profile. The agent must not promise coverage, premium level or warranty compliance.$$, 'internal insurance baseline', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'KYC and Beneficial Ownership', 'KYC, AML and Sanctions', 'Identity and ownership checks before sensitive work.', $$For serious transactions, capture legal buyer/seller identity, beneficial owner, source of funds path, sanctions exposure, politically exposed person concerns, representative authority and corporate structure. High-risk items require admin review before proceeding.$$, 'internal AML baseline', 'verified');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Sanctions Screening Trigger Points', 'KYC, AML and Sanctions', 'When sanctions review must be escalated.', $$Escalate if a party, beneficial owner, vessel, flag, location, bank, manager, charterer or counterparty has exposure to sanctioned jurisdictions, blocked persons, unclear ownership or unusual payment routes. Do not continue sensitive disclosure until cleared.$$, 'internal AML baseline', 'verified');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Yacht Valuation Inputs', 'Valuation and Market', 'Inputs that affect yacht pricing and market position.', $$Valuation depends on builder, model, year, length, volume, condition, refit history, engine hours, class/flag status, pedigree, layout, market comparables, location, seasonality, seller motivation and recent survey findings. Avoid exact valuation claims without data.$$, 'internal valuation baseline', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Comparable Sales Discipline', 'Valuation and Market', 'How to treat comparable yacht data.', $$Comparable sales should be treated carefully because asking prices, achieved prices and confidential discounts differ. The agent should separate asking data from confirmed sale data and mark reliability of each comparable.$$, 'internal valuation baseline', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Refit History and Maintenance Records', 'Refit and Technical', 'Why refit records matter in brokerage.', $$Recent refits can support value, but only if scope, invoices, shipyard, warranties, class impact and technical documentation are clear. Lack of records can increase buyer risk and should be surfaced before drafting claims.$$, 'internal technical baseline', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Technical Red Flags', 'Refit and Technical', 'Technical issues that should trigger deeper review.', $$Red flags include overdue class items, major engine issues, corrosion, osmosis on composites, stabilizer problems, generator unreliability, poor maintenance records, accident history, incomplete refit, water ingress, title/document gaps and unusually low asking price.$$, 'internal technical baseline', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Marina and Berthing Constraints', 'Marinas and Berthing', 'Why berth availability affects yacht ownership and deals.', $$Berthing can be constrained by length, beam, draft, season, location, marina waitlists, commercial use, insurance and local permits. For buyers, ask intended home port and cruising region early.$$, 'internal operations baseline', 'medium');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Delivery and Handover Checklist', 'Crew and Operations', 'Operational items around closing and handover.', $$Handover planning may include delivery location, crew, fuel, spares, manuals, certificates, keys, tenders/toys, inventory, insurance start, registry changes, management setup and berth arrangements. Sensitive timing and payment instructions require approval.$$, 'internal operations baseline', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Flag Registry: Cayman Islands Awareness', 'Flags and Registration', 'Cayman Islands is a common yacht registry reference point.', $$Cayman Islands is a prominent yacht registry. For any Cayman-related question, verify the current registration type, vessel eligibility, required documents, surveys, ownership structure and whether the yacht is private or commercial with the Cayman Islands Shipping Registry or specialist counsel.$$, 'https://www.cishipping.com', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Flag Registry: Marshall Islands Awareness', 'Flags and Registration', 'Marshall Islands is a common yacht registry reference point.', $$The Republic of the Marshall Islands registry is often used for yachts and commercial vessels. For RMI-related questions, verify current yacht registration requirements, entity ownership, private or commercial status, mortgage recording and certificate requirements with the official registry or specialist counsel.$$, 'https://www.register-iri.com/yachts/', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Flag Registry: Malta Awareness', 'Flags and Registration', 'Malta is a common EU yacht registration and commercial yacht reference point.', $$Malta is frequently relevant for yacht registration and commercial yacht structures. For Malta-related questions, verify current Transport Malta requirements, commercial yacht code status, VAT/tax facts, ownership and operating model with official sources or specialist counsel.$$, 'https://www.transport.gov.mt/maritime', 'high');
select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Source Reliability Rules for Yacht Knowledge', 'Advisory Boundaries', 'How the agent should trust and cite stored yacht knowledge.', $$Prefer official registries, government maritime authorities, IMO/ILO publications, class society documents and signed deal documents. Treat broker blogs and marketing pages as medium or low reliability unless confirmed. Always preserve source and updated date.$$, 'internal source policy', 'verified');

select public.seed_agent_knowledge_entry('yacht-broker-agent', 'Knowledge Update Workflow', 'Advisory Boundaries', 'How new yacht knowledge should be added later.', $$For new topics, collect source URL, publication date, jurisdiction, short summary, operational use, risk level and approval requirement. Save as knowledge entry only after admin review. For legal/tax/compliance content, store as guidance for questions and escalation, not final advice.$$, 'internal source policy', 'verified');

drop function public.seed_agent_knowledge_entry(text, text, text, text, text, text, text);
